#!/bin/bash

sudo su
apt install python3-dev libffi-dev gcc libssl-dev python3-selinux python3-setuptools -y

#virtual environment setup
python3 -m pip install --user virtualenv
python3 -m venv ansible-env

#use virtual environment
source ./ansible-env/bin/activate

#install ansible
pip3 install ansible==2.9

#installing octopus via git repo
git clone https://github.com/ceph/ceph-ansible.git
cd ceph-ansible
git checkout stable-5.0
pip3 install -r requirements.txt

#editing hosts file
echo "[mons]
controller

[mgrs]
controller

[mdss]
controller

[rgws]
controller

[osds]
storage devices="['/dev/disk/by-id/scsi-SQEMU_QEMU_HARDDISK_e0628122-562c-4a86-beb1-17347e964f8e','/dev/disk/by-id/scsi-SQEMU_QEMU_HARDDISK_4e427311-c961-4740-ae31-2ad89f79cc68','/dev/disk/by-id/scsi-SQEMU_QEMU_HARDDISK_e044a28f-f89c-44c6-89c5-e962584e929c','/dev/disk/by-id/scsi-SQEMU_QEMU_HARDDISK_8ec450ed-ee13-4e0f-aa5b-e3489ca129bb']"

[grafana-server]
controller" >hosts

#editing all.yml
#verfiy storage devices before deploying
echo '---
# Variables here are applicable to all host groups NOT roles

# This sample file generated by generate_group_vars_sample.sh

# Dummy variable to avoid error because ansible does not recognize the
# file as a good configuration file when no variable in it.
dummy:

ntp_service_enabled: true
ceph_origin: "repository"
ceph_repository: "community"
ceph_stable_release: "octopus"
public_network: "10.0.3.0/24"
monitor_interface: "ens5"
radosgw_interface: "ens5"
containerized_deployment: false
dashboard_admin_password: "Krak3n"
grafana_admin_password: "Lev1athan"' >./group_vars/all.yml

#editing main.yml
echo '---
ceph_osd_pool_default_size: 1
ceph_osd_pool_default_min_size: 1
ceph_osd_pool_default_crush_rule: -1
ceph_osd_pool_default_crush_rule_name: "replicated_rule"' >./roles/ceph-defaults/vars/main.yml